apiVersion: v1
kind: Service 
metadata:
  name: {{ .Release.Name }}-svc
spec:
  type: NodePort
  ports:
    - name: http
      targetPort: http
      protocol: TCP
      port: 80
  selector:
    app: hello-world
